# Generated by Django 4.0.1 on 2022-01-24 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
