# Generated by Django 4.0.1 on 2022-01-24 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_plan_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='date_created',
        ),
    ]
