# Generated by Django 4.0 on 2022-07-18 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_archive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
